package com.vatril.funktrainer

enum class RadioChars(val text: String,val character:Char) {
    A("alpha", 'A'),
    B("bravo", 'B'),
    C("charlie", 'C'),
    D("delta", 'D'),
    E("echo", 'E'),
    F("foxtrot", 'F'),
    G("golf", 'G'),
    H("hotel", 'H'),
    I("india", 'I'),
    J("juliet", 'J'),
    K("kilo", 'K'),
    L("lima", 'L'),
    M("mike", 'M'),
    N("november", 'N'),
    O("oscar", 'O'),
    P("papa", 'P'),
    Q("quebec", 'Q'),
    R("romeo", 'R'),
    S("sierra", 'S'),
    T("tango", 'T'),
    U("uniform", 'U'),
    V("victor", 'V'),
    W("whiskey", 'W'),
    X("x-ray", 'X'),
    Y("yankee", 'Y'),
    Z("zulu", 'Z'),
    Z0("zero", '0'),
    Z1("one", '1'),
    Z2("two", '2'),
    Z3("three", '3'),
    Z4("four", '4'),
    Z5("five", '5'),
    Z6("six", '6'),
    Z7("seven", '7'),
    Z8("eight", '8'),
    Z9("nine", '9'),

}